version: '3.8'

services:
  gateway:
    container_name: gateway
    build:
      context: .
      target: development
      args:
        - APP=gateway
    command: "npm run start:dev gateway"
    networks:
      - backend
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  user-service:
    container_name: user_service
    build:
      context: .
      target: development
      args:
        - APP=users
    command: "npm run start:dev users"
    expose:
      - "50051"
    networks:
      - backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


networks:
  backend: