version: '3.8'

services:
  gateway:
    container_name: gateway
    build:
      context: .
      args:
        - APP=gateway
    ports:
      - '3000:3000'
    restart: always
  user-service:
    container_name: user_service
    build:
      context: .
      args:
        - APP=users
    ports:
      - '3001:3001'
    restart: always
