version: '3.8'

services:
  gateway:
    container_name: gateway
    build:
      context: .
      args:
        - APP=gateway
    ports:
      - '3000:3000'
    restart: always
  user-service:
    container_name: user_service
    build:
      context: .
      args:
        - APP=users
    ports:
      - '3001:3001'
    restart: always
    env_file:
      - .env
    depends_on:
      - user_service_db
  user_service_db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_DATABASE}
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    container_name: "user_service_db"
    expose:
      - 5432
